# Generated by Django 5.0.4 on 2024-04-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_users_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='UserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_UserID', to='tasks.users'),
        ),
    ]
